import '../language_screen/widgets/listchineses_item_widget.dart';import '../language_screen/widgets/listenglishuk_item_widget.dart';import 'controller/language_controller.dart';import 'models/listchineses_item_model.dart';import 'models/listenglishuk_item_model.dart';import 'package:flutter/material.dart';import 'package:jobpro/core/app_export.dart';import 'package:jobpro/widgets/app_bar/appbar_image.dart';import 'package:jobpro/widgets/app_bar/appbar_title.dart';import 'package:jobpro/widgets/app_bar/custom_app_bar.dart';class LanguageScreen extends GetWidget<LanguageController> {const LanguageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA70001, appBar: CustomAppBar(height: getVerticalSize(51), leadingWidth: getHorizontalSize(48), leading: AppbarImage(svgPath: ImageConstant.imgGroup162799, margin: getMargin(left: 24, top: 13, bottom: 14), onTap: () {onTapArrowbackone();}), centerTitle: true, title: AppbarTitle(text: "lbl_language".tr)), body: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 28, right: 24, bottom: 28), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: getPadding(left: 16, top: 21, right: 16, bottom: 21), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: getPadding(top: 2), child: Text("msg_suggested_languages".tr, style: CustomTextStyles.labelLargeSemiBold)), Expanded(child: Padding(padding: getPadding(top: 16), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: getPadding(top: 7.0, bottom: 7.0), child: SizedBox(width: getHorizontalSize(295), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.indigo50)));}, itemCount: controller.languageModelObj.value.listenglishukItemList.value.length, itemBuilder: (context, index) {ListenglishukItemModel model = controller.languageModelObj.value.listenglishukItemList.value[index]; return ListenglishukItemWidget(model);}))))])))), Expanded(child: SizedBox(width: double.maxFinite, child: Container(margin: getMargin(top: 24, bottom: 5), padding: getPadding(all: 16), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: getPadding(top: 3), child: Text("lbl_other_languages".tr, style: CustomTextStyles.labelLargeSemiBold)), Expanded(child: Padding(padding: getPadding(top: 19), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: getPadding(top: 8.0, bottom: 8.0), child: SizedBox(width: getHorizontalSize(295), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.indigo50)));}, itemCount: controller.languageModelObj.value.listchinesesItemList.value.length, itemBuilder: (context, index) {ListchinesesItemModel model = controller.languageModelObj.value.listchinesesItemList.value[index]; return ListchinesesItemWidget(model);}))))]))))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowbackone() { Get.back(); } 
 }
